name: Publish to JSR

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'
      - '.github/workflows/publish.yml'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Publish @ts-api-kit/core
        run: |
          cd packages/core
          npx jsr publish --allow-slow-types --allow-dirty

      - name: Publish @ts-api-kit/compiler
        run: |
          cd packages/compiler
          npx jsr publish --allow-slow-types --allow-dirty

